kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ledger-db
  annotations:
    volume.beta.kubernetes.io/storage-class: px-csi-db-encrypted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

